// Helper: return Tailwind class from a accord
export function getAccordColor(accord) {
  const family = colorDictionary[accord.toLowerCase()];
  return family ? `bg-${family}` : "bg-fallback";
}
export function getNoteColor(note) {
  const family = colorDictionary[note.toLowerCase()];
  return family ? `border-${family} border-2` : "border-fallback border-2";
}

// A simple helper function to get the color class
export function getGenderColor(gender) {
  switch (gender.toLowerCase()) {
    case "men":
      return "bg-men text-neutral-cool-200";
    case "women":
      return "bg-women text-neutral-cool-200";
    case "unisex":
      return "bg-unisex text-neutral-cool-200";
    default:
      return "bg-gray-200"; // Fallback color
  }
};

// DATA FROM FRAGRANTICA
// Map notes to fragrance families
export const colorDictionary = {
  // Main Accords (might overlap with specific notes)
  aldehydic: "soft-floral",
  soapy: "soft-floral",
  amber: "amber",
  animalic: "amber",
  aquatic: "water-marine",
  aromatic: "fresh-aromatic",
  citrus: "citrus",
  earthy: "mossy-woods",
  floral: "floral",
  fresh: "fresh-aromatic",
  "fresh spicy": "fresh-aromatic",
  fruity: "fruity",
  green: "green",
  herbal: "fresh-aromatic",
  lactonic: "soft-floral",
  leather: "dry-woods",
  marine: "water-marine",
  mossy: "mossy-woods",
  musky: "soft-amber",
  oud: "woody-amber",
  ozonic: "water-marine",
  powdery: "soft-floral",
  salty: "water-marine",
  smoky: "dry-woods",
  "soft spicy": "soft-amber",
  sweet: "floral-amber",
  tropical: "fruity",
  "warm spicy": "woody-amber",
  "white floral": "floral",
  woody: "woody",
  "yellow floral": "floral",

  // Citrus Family
  bergamot: "citrus",
  bigarade: "citrus",
  "bitter orange": "citrus",
  "blood orange": "citrus",
  "buddha's hand": "citrus",
  calamansi: "citrus",
  "candied lemon": "citrus",
  "chen pi": "citrus",
  chinotto: "citrus",
  citron: "citrus",
  "citrus japonica": "citrus",
  "citrus water": "water-marine",
  citruses: "citrus",
  clementine: "citrus",
  "finger lime": "citrus",
  grapefruit: "citrus",
  "grapefruit leaf": "green",
  "grapefruit peel": "citrus",
  "green tangerine": "citrus",
  hassaku: "citrus",
  "hatkora lemon": "citrus",
  "kaffir lime": "citrus",
  kumquat: "citrus",
  lemon: "citrus",
  "lemon balm": "green",
  "lemon myrtle": "green",
  "lemon tree": "green",
  "lemon verbena": "green",
  "lemon zest": "citrus",
  lemongrass: "green",
  lime: "citrus",
  limetta: "citrus",
  "litsea cubeba": "citrus",
  "mandarin orange": "citrus",
  mandora: "citrus",
  "methyl pamplemousse": "citrus",
  neroli: "floral",
  orange: "citrus",
  "palestinian sweet lime": "citrus",
  "perfume lemon": "citrus",
  petitgrain: "fresh-aromatic",
  pokan: "citrus",
  pomelo: "citrus",
  quenepa: "fruity",
  rangpur: "citrus",
  "red mandarin": "citrus",
  "rind bergamot": "citrus",
  shiikuwasha: "citrus",
  "sudachi citrus": "citrus",
  tangelo: "citrus",
  tangerine: "citrus",
  "tangerine zest": "citrus",
  yuzu: "citrus",

  // Fruits, Veggies, Nuts Family
  "acai berry": "fruity",
  acerola: "fruity",
  acorn: "woody",
  "akebia fruit": "fruity",
  almond: "amber",
  apple: "fruity",
  "apple juice": "fruity",
  "apple pulp": "fruity",
  "apple sherbet": "fruity",
  apricot: "fruity",
  "arctic bramble": "fruity",
  argan: "woody",
  artichoke: "green",
  ashberry: "fruity",
  banana: "fruity",
  barberry: "fruity",
  bearberry: "fruity",
  beetroot: "green",
  "bitter melon": "green",
  "black cherry": "fruity",
  "black currant": "fruity",
  "black sapote": "fruity",
  "black walnut": "woody",
  blackberry: "fruity",
  blackthorn: "fruity",
  blueberry: "fruity",
  boysenberry: "fruity",
  "brazil nut": "woody",
  breadnut: "woody",
  buriti: "fruity",
  "burning cherry": "amber",
  "cabernet grape": "fruity",
  candlenut: "woody",
  cantaloupe: "water-marine",
  starfruit: "fruity",
  carrot: "green",
  cashew: "woody",
  "cassowary fruit": "fruity",
  cauliflower: "green",
  cepes: "dry-woods",
  chayote: "green",
  cherimoya: "fruity",
  cherry: "fruity",
  "cherry jam": "fruity",
  chestnut: "woody-amber",
  "chia seed": "green",
  chickpeas: "green",
  "chinese magnolia": "floral",
  cloudberry: "fruity",
  "coco de mer": "woody-amber",
  "cocoa shell": "amber",
  coconut: "fruity",
  "coconut water": "water-marine",
  "cogumelo porcino": "dry-woods",
  conifer: "woody",
  corn: "green",
  "corn silk": "green",
  "count's fruit": "fruity",
  cranberry: "fruity",
  cucumber: "water-marine",
  "cupuaçu, cupuassu, copoasu": "fruity",
  "currant leaf and bud": "green",
  "cyperus scariosus": "woody",
  "daikon radish": "green",
  "dark plum wu mei": "fruity",
  dewberry: "fruity",
  "dried apple crisp": "fruity",
  "dried apricot": "fruity",
  "dried fruits": "fruity",
  durian: "fruity",
  elderberry: "fruity",
  "feijoa fruit": "fruity",
  fig: "fruity",
  "fig leaf": "green",
  "fig milk": "green",
  "forest fruits": "fruity",
  "frosted berries": "fruity",
  "fruit salad": "fruity",
  "fruity notes": "fruity",
  "fuji apple": "fruity",
  "gariguette strawberry": "fruity",
  genipapo: "fruity",
  "goji berries": "fruity",
  gooseberry: "fruity",
  grains: "green",
  "grape seed": "woody",
  grapes: "fruity",
  "green anjou pears": "fruity",
  "green grape": "fruity",
  "green pear": "fruity",
  "green plum": "fruity",
  greengage: "fruity",
  "ground cherry": "fruity",
  guarana: "fruity",
  guava: "fruity",
  hazelnut: "woody",
  "hog plum": "fruity",
  "honeydew melon": "water-marine",
  "isabella grape": "fruity",
  jabuticaba: "fruity",
  jackfruit: "fruity",
  "japanese loquat": "fruity",
  "jobs tears": "green",
  kiwi: "fruity",
  kumbaru: "woody",
  lingonberry: "fruity",
  litchi: "fruity",
  loganberry: "fruity",
  "longan berries": "fruity",
  lucuma: "fruity",
  macadamia: "woody",
  mahonia: "fruity",
  malt: "amber",
  mamey: "fruity",
  mango: "fruity",
  mangosteen: "fruity",
  maninka: "fruity",
  "marian plum": "fruity",
  medlar: "fruity",
  melon: "water-marine",
  millet: "green",
  mirabelle: "fruity",
  "miracle berry": "fruity",
  "moepel accord": "amber",
  mulberry: "fruity",
  "mung bean": "green",
  mushroom: "dry-woods",
  "nashi pear": "fruity",
  nectarine: "fruity",
  nutty: "woody-amber",
  "okra seeds": "green",
  olive: "green",
  papaya: "fruity",
  passionfruit: "fruity",
  pea: "green",
  peach: "fruity",
  peanut: "woody",
  pear: "fruity",
  pecan: "woody",
  persimmon: "fruity",
  "peruvian pepper": "fresh-aromatic",
  pineapple: "fruity",
  "pinot noir grapes": "fruity",
  pistachio: "woody",
  pitahaya: "fruity",
  pitanga: "fruity",
  plantain: "fruity",
  plum: "fruity",
  pomegranate: "fruity",
  potato: "green",
  "prickly pear": "fruity",
  pumpkin: "green",
  "purple yam": "green",
  "quandong desert peach": "fruity",
  quince: "fruity",
  rambutan: "fruity",
  raspberry: "fruity",
  "red apple": "fruity",
  "red berries": "fruity",
  "red currant": "fruity",
  "red fruits": "fruity",
  "red fruits smoothie": "fruity",
  "red mulberry": "fruity",
  rhubarb: "green",
  "roasted nuts": "woody-amber",
  "rose apple": "fruity",
  salak: "fruity",
  santol: "fruity",
  sapodilla: "fruity",
  sarsaparilla: "green",
  "sea buckthorn": "fruity",
  seriguela: "fruity",
  "serrano pepper": "green",
  "shea butter": "amber",
  "shea nuts": "woody",
  silverberry: "fruity",
  snowberry: "fruity",
  "sour cherry": "fruity",
  soursop: "fruity",
  soybean: "green",
  squash: "green",
  "star apple": "fruity",
  strawberry: "fruity",
  "strawberry jam": "fruity",
  tamanu: "woody",
  tapioca: "green",
  taro: "green",
  tayberry: "fruity",
  tomato: "green",
  "tropical fruits": "fruity",
  tropicalone: "fruity",
  tucumã: "fruity",
  vegetal: "green",
  walnut: "woody",
  "walnut milk": "woody-amber",
  "water fruit": "water-marine",
  watermelon: "water-marine",
  wattleseed: "green",
  "white currant": "fruity",
  "white grape": "fruity",
  "white mulberry": "fruity",
  "wild strawberry": "fruity",
  "williams pear": "fruity",
  winterberry: "fruity",
  wolfberry: "fruity",
  "yellow cherry": "fruity",
  "yellow fruits": "fruity",
  "yuca cassava": "green",
  yumberry: "fruity",

  // Floral Family
  abelia: "floral",
  acacia: "floral",
  "acerola blossom": "floral",
  "african marigold": "floral",
  aglaia: "floral",
  "alba rose": "floral",
  albizia: "floral",
  "almond blossom": "floral",
  alpinia: "floral",
  alstroemeria: "floral",
  althaea: "floral",
  alumroot: "green",
  alyssum: "floral",
  amarillys: "floral",
  "amazon moonflower": "floral",
  anemone: "floral",
  "angel's trumpet": "floral",
  "apple blossom": "floral",
  "apricot blossom": "floral",
  "ashoka flower": "floral",
  "asian clintonia": "floral",
  astragalus: "green",
  azalea: "floral",
  "azteca lily": "floral",
  "baby’s breath": "soft-floral",
  "banana flower": "floral",
  "banksia australian": "floral",
  begonia: "floral",
  belladona: "floral",
  bellflower: "floral",
  "bergamot blossom": "floral",
  "bird cherry": "floral",
  "black currant blossom": "floral",
  "blackberry blossom": "floral",
  "blue lilies": "floral",
  "blue poppy": "floral",
  bluebell: "floral",
  bottlebrush: "floral",
  bougainvillea: "floral",
  "bread flower": "floral",
  bromelia: "floral",
  buddleia: "floral",
  "butomus umbellatus": "floral",
  buttercup: "floral",
  "cacao blossom": "floral",
  "cactus blossom": "floral",
  calendula: "floral",
  "calla lily": "floral",
  camellia: "floral",
  "campion flower": "floral",
  cananga: "floral",
  "cannonball flower": "floral",
  "carambola blossom": "floral",
  "cardamom flower": "floral",
  carnation: "floral",
  "cashew flower": "floral",
  celosia: "floral",
  "chai hu": "fresh-aromatic",
  chamomile: "soft-floral",
  champaca: "floral",
  "cherry blossom": "soft-floral",
  "chimonanthus or wintersweet": "floral",
  "china rose": "floral",
  "chinotto blossom": "floral",
  "chocolate flower": "floral",
  "christmas tree or flame tree": "woody",
  chrysanthemum: "floral",
  "cistus incanus": "amber",
  clematis: "floral",
  clover: "green",
  "coconut blossom": "floral",
  "coffee blossom": "floral",
  "cornflower sultan seeds": "green",
  "cosmos flower": "floral",
  costus: "woody",
  "cotton flower": "soft-floral",
  "creamy flowers": "floral",
  "crinum lily": "floral",
  "cucumber flower": "floral",
  cyclamen: "soft-floral",
  dahlia: "floral",
  daisy: "soft-floral",
  dandelion: "green",
  daphne: "floral",
  daylily: "floral",
  deadnettle: "green",
  delonix: "floral",
  "desert rose": "floral",
  dianthus: "floral",
  diviniris: "floral",
  "dogwood blossom": "floral",
  "dove tree": "woody",
  "dried rose": "soft-floral",
  "dyer's greenweed": "green",
  edelweiss: "floral",
  "eglantine rose": "floral",
  elderflower: "floral",
  encian: "green",
  "erigeron (fleabane)": "green",
  euphorbia: "floral",
  "eustoma | lisianthus": "floral",
  evergreen: "woody",
  "field scabious": "floral",
  "fig blossom": "floral",
  "fire lily": "floral",
  "flamingo flower (anthurium)": "floral",
  flax: "green",
  floral: "floral",
  "forget me not": "soft-floral",
  fragonia: "fresh-aromatic",
  freesia: "soft-floral",
  "french marigold": "floral",
  "fringed pink": "floral",
  fuchsia: "floral",
  geranium: "floral",
  gerbera: "floral",
  gladiolus: "floral",
  goldenrod: "green",
  gorse: "floral",
  grapeflower: "floral",
  "great burnet": "woody",
  "green nard": "green",
  "green tea flower": "floral",
  grevillea: "floral",
  "guava blossom": "floral",
  guayacan: "woody",
  "gustavia flower": "floral",
  hawthorn: "floral",
  "hazel blossom": "floral",
  heather: "floral",
  heliotrope: "soft-floral",
  "hellabore flower": "floral",
  hemlock: "green",
  hibiscus: "floral",
  "hoary stock": "floral",
  "holly flower": "floral",
  hollyhock: "floral",
  "honeybush or cyclopia": "green",
  "honeydew blossom": "floral",
  hortensia: "floral",
  "hoya carnosa wax plant": "floral",
  hyacinth: "floral",
  hyssop: "fresh-aromatic",
  impatiens: "floral",
  inula: "green",
  iris: "soft-floral",
  "iris butter": "soft-floral",
  "iris pallida": "soft-floral",
  jacaranda: "floral",
  "jade flower": "floral",
  "jarana flower": "floral",
  "jasmine orchid": "floral",
  "jujube blossom": "floral",
  kadam: "floral",
  "kangaroo paw": "floral",
  kanuka: "fresh-aromatic",
  karmaflor: "floral",
  "kiwi blossom": "floral",
  kudzu: "floral",
  laburnum: "floral",
  "lady of the night flower": "floral",
  "lady slipper orchid": "floral",
  "lamduan flower": "floral",
  lamprocapnos: "floral",
  lantana: "floral",
  larkspur: "floral",
  "laurel blossom": "floral",
  lavender: "soft-floral",
  leatherwood: "woody",
  ledum: "green",
  liatris: "floral",
  liatrix: "floral",
  "licorice flower": "floral",
  lilac: "floral",
  "lily-of-the-valley": "soft-floral",
  "lime blossom": "floral",
  "litchi blossom": "floral",
  longoza: "floral",
  lotus: "water-marine",
  lupin: "floral",
  "lydia broom": "floral",
  lysylang: "floral",
  "macadamia flower": "floral",
  magnolia: "floral",
  "magnolia brooklynensis": "floral",
  "magnolia leaf": "green",
  mahonia: "floral",
  mahonial: "floral",
  malva: "floral",
  "mango blossom": "floral",
  "mariposa lily": "floral",
  mayflower: "floral",
  meadowsweet: "floral",
  melilotus: "green",
  "melissa flower": "floral",
  michelia: "floral",
  "michelia leaf": "green",
  mignonette: "floral",
  milkweeds: "floral",
  mimosa: "soft-floral",
  "mimusops elengi": "floral",
  mirabilis: "floral",
  monarda: "fresh-aromatic",
  "monoi oil": "floral",
  "moringa blossom": "floral",
  "morning glory flower": "floral",
  "moss flox": "mossy-woods",
  myrtle: "fresh-aromatic",
  narcissus: "floral",
  nard: "woody",
  nasturtium: "floral",
  "nectarine blossom": "floral",
  "nerium oleander": "floral",
  nigella: "woody",
  "night blooming jasmine": "floral",
  "nom maew": "floral",
  "olive flower": "floral",
  opium: "floral-amber",
  "orange cassia tree": "floral",
  "orange flower water": "floral",
  "orchard blossom": "floral",
  orchid: "floral",
  "orchid black diamond": "floral",
  "orchid cactus": "floral",
  "orchid pink leopard": "floral",
  ornithogalum: "floral",
  "orris root": "soft-floral",
  osmanthus: "floral",
  pansy: "floral",
  "papaya blossom": "floral",
  paramela: "fresh-aromatic",
  "passion flower": "floral",
  pataqueira: "woody",
  "peach blossom": "floral",
  "pear blossom": "floral",
  pelargonium: "floral",
  peony: "soft-floral",
  periwinkle: "floral",
  petalia: "floral",
  petunia: "floral",
  phlox: "floral",
  "pineapple blossom": "floral",
  "pink flamingo heliconia": "floral",
  "pink lily": "floral",
  "pinwheel flower": "floral",
  "pitahaya flower": "floral",
  pittosporum: "floral",
  "plum blossom": "floral",
  plumeria: "floral",
  poinsettia: "floral",
  "pomegranate blossom": "floral",
  poppy: "soft-floral",
  primrose: "floral",
  "princess tree": "woody",
  privet: "floral",
  protea: "floral",
  prunella: "floral",
  "purple coneflower": "floral",
  "queen of the night flower": "floral",
  "rangoon creeper": "floral",
  "raspberry blossom": "floral",
  "redwood flower": "woody",
  reseda: "floral",
  rhododendron: "floral",
  "rosa alba": "floral",
  "rosa rubiginosa": "floral",
  rose: "floral",
  "rose hip": "fruity",
  "rose japanese": "floral",
  "rose mallow": "floral",
  "rose otto": "floral",
  "rose petals": "soft-floral",
  "rose queen": "floral",
  "rose tea": "floral",
  "rosebay willowherb": "floral",
  rosebud: "soft-floral",
  roselle: "fruity",
  rosyfolia: "floral",
  safflower: "floral",
  sainfoins: "floral",
  "sand lily": "floral",
  "sandalwood flower": "floral",
  santolina: "fresh-aromatic",
  "saucer magnolia": "floral",
  "sea daffodil": "water-marine",
  "siberian rhododendron": "floral",
  "silk tree blossom": "floral",
  "silverthorn flower": "floral",
  "skeleton flower": "floral",
  smoketree: "woody",
  snakeroot: "woody",
  "snow lotus": "floral",
  snowdrops: "soft-floral",
  "solomon's seal": "green",
  "sophora toromiro flower": "floral",
  "sour cherry blossom": "floral",
  "spanish broom": "floral",
  spiraea: "floral",
  "st. john's wort": "green",
  starflower: "floral",
  "strawberry flower": "floral",
  strelitzia: "floral",
  "strobilanthes callosa": "floral",
  sunflower: "floral",
  "sweet pea": "soft-floral",
  "taif rose": "floral",
  tamarisk: "woody",
  "tobacco blossom": "floral",
  "transparent flowers": "floral",
  trillium: "floral",
  tulip: "floral",
  "vanilla bahiana": "floral-amber",
  viburnum: "floral",
  violet: "floral",
  "violet woodsorrel": "green",
  wallflower: "floral",
  waratah: "floral",
  "water flowers": "water-marine",
  "water hyacinth": "water-marine",
  "water lily": "water-marine",
  "weeping cherry blossom": "soft-floral",
  "white champaca": "floral",
  "white dahlia": "floral",
  "white ginger lily": "floral",
  "white lace flower": "floral",
  "white tea blossom": "floral",
  wildflowers: "floral",
  "winter daphne": "floral",
  wisteria: "floral",
  wrightia: "floral",
  "yellow bells": "floral",
  "yellow flowers": "floral",
  "ylang-ylang": "floral",
  "yunnan osmanthus": "floral",
  "yuzu flower": "floral",
  zinnia: "floral",

  // White Flowers Family
  "arum lily": "floral",
  belanis: "floral",
  "black locust": "floral",
  boronia: "floral",
  carissa: "floral",
  datura: "floral-amber",
  frangipani: "floral-amber",
  gardenia: "floral-amber",
  "grapefruit blossom": "floral",
  honeysuckle: "floral",
  jasmine: "floral-amber",
  "karo-karounde": "floral-amber",
  "lemon blossom": "floral",
  lily: "floral",
  "mandarin orange blossom": "floral",
  melati: "floral",
  "mock orange": "floral",
  "moon flower": "soft-floral",
  "night blooming cereus": "floral-amber",
  "orange blossom": "floral",
  stephanotis: "floral",
  syringa: "floral",
  "tangerine blossom": "floral",
  "tiare flower": "floral-amber",
  tuberose: "floral-amber",
  "white flowers": "floral",
  "white tobacco": "floral-amber",

  // Green Herbs and Fourges Family
  "acronychia pedunculata": "green",
  agave: "green",
  algae: "water-marine",
  "aloe vera": "green",
  "ammophila beach grass": "green",
  angelica: "fresh-aromatic",
  "angelica root": "woody",
  "apple mint": "fresh-aromatic",
  arnica: "green",
  aromatic: "fresh-aromatic",
  artemisia: "fresh-aromatic",
  asparagus: "green",
  "assam tea": "fresh-aromatic",
  avocado: "green",
  "azolla water fern": "water-marine",
  "bagas de zimbro": "fresh-aromatic",
  "banana leaf": "green",
  barley: "green",
  barrenwort: "green",
  basil: "fresh-aromatic",
  "bay essence": "fresh-aromatic",
  beachheather: "green",
  "behini tree": "woody",
  "betel leaf": "green",
  bigarane: "fresh-aromatic",
  "black currant leaf": "green",
  "blackberry leaf": "green",
  "blue bugle": "green",
  borage: "green",
  borneol: "woody",
  bran: "green",
  "buchu or agathosma": "green",
  buckwheat: "green",
  "buckwheat tea": "fresh-aromatic",
  bulrush: "green",
  burdock: "green",
  cactus: "green",
  calamus: "woody",
  calycanthus: "floral",
  cangzhu: "green",
  cannabis: "green",
  caper: "green",
  capitiu: "green",
  "carnation leaves": "green",
  catnip: "green",
  "cedar leaves": "woody",
  "cedar roots": "dry-woods",
  celery: "green",
  "celery seeds": "fresh-aromatic",
  "centella asiatica": "green",
  chaparral: "green",
  "cherry leaf": "green",
  chicory: "green",
  "chinese medicinal herbs": "green",
  chive: "fresh-aromatic",
  chlorophyll: "green",
  "chuan xiong": "green",
  cilantro: "fresh-aromatic",
  "citron leaf": "green",
  "clary sage": "fresh-aromatic",
  coca: "green",
  coleus: "green",
  "creosote bush": "green",
  crithmum: "water-marine",
  davana: "fresh-aromatic",
  "deer tongue grass": "green",
  "dried fallen leaves": "mossy-woods",
  "duck poo oolong": "fresh-aromatic",
  "earl grey tea": "fresh-aromatic",
  "fermented tea": "fresh-aromatic",
  fern: "green",
  flouve: "green",
  "fo ti ho shou wu": "green",
  "fougere accord": "fresh-aromatic",
  "fresh evergreen": "woody",
  "gajumaru banyan": "woody",
  galbanum: "green",
  garlic: "green",
  genmaicha: "fresh-aromatic",
  "geranium macrorrhizum zdravetz": "green",
  ginkgo: "green",
  ginseng: "green",
  "grape leaves": "green",
  grass: "green",
  "green branches": "green",
  "green chilli": "green",
  "green forest": "woody",
  green: "green",
  "green pepper": "green",
  "green sap": "green",
  gromwell: "green",
  "guao or maiden plum": "green",
  "gyokuro tea": "fresh-aromatic",
  "hat straw": "dry-woods",
  hay: "dry-woods",
  henna: "green",
  hops: "fresh-aromatic",
  horseweed: "green",
  "huang lian": "green",
  immortelle: "floral-amber",
  ivy: "green",
  jambu: "green",
  "jatamansi or spikenard": "woody",
  "jin xuan tea leaves": "fresh-aromatic",
  jojoba: "green",
  juniper: "fresh-aromatic",
  katrafay: "woody",
  "katsura leaf": "green",
  "keemun tea": "fresh-aromatic",
  khella: "green",
  kunzea: "fresh-aromatic",
  laminaria: "water-marine",
  "lantana leaf": "green",
  "lapsang souchong tea": "fresh-aromatic",
  "laurissilva forest": "woody",
  "lesser calamint": "fresh-aromatic",
  lettuce: "green",
  "lily-of-the-valley leaves": "green",
  "limnophila aromatica": "green",
  "linaloe berry": "green",
  "lishan tea": "fresh-aromatic",
  "longjing tea": "fresh-aromatic",
  "lovage root": "green",
  "ma-kwaen": "fresh-aromatic",
  mandrake: "green",
  marigold: "floral",
  marjoram: "fresh-aromatic",
  "matcha tea": "fresh-aromatic",
  mate: "fresh-aromatic",
  "melilot or sweet clover": "green",
  "mimosa leaves": "green",
  mint: "fresh-aromatic",
  mistletoe: "green",
  mugwort: "green",
  naswar: "green",
  nettle: "green",
  "nut grass": "green",
  "oak leaves": "woody",
  oat: "green",
  "olive leaf": "green",
  "oolong tea": "fresh-aromatic",
  "orchid leaf": "green",
  oregano: "fresh-aromatic",
  "palm leaf": "green",
  palmarosa: "fresh-aromatic",
  "pandan leaf": "green",
  pandanus: "green",
  parsley: "fresh-aromatic",
  "peach leaf": "green",
  "pear leaf": "green",
  pennyroyal: "fresh-aromatic",
  pesto: "fresh-aromatic",
  petrichor: "green",
  peyote: "green",
  physcool: "fresh-aromatic",
  polygonum: "green",
  "portulaca or pigweed": "green",
  posidonia: "water-marine",
  "pu'er tea": "fresh-aromatic",
  purslane: "green",
  "raspberry leaf": "green",
  "red algae": "water-marine",
  reed: "green",
  rice: "green",
  "rooibos red tea": "fresh-aromatic",
  roots: "woody",
  "rose leaf": "green",
  "rose thorn": "woody",
  rosemary: "fresh-aromatic",
  roseroot: "woody",
  rue: "green",
  rumex: "green",
  rye: "green",
  "sabah snake grass": "green",
  sage: "fresh-aromatic",
  sansevieria: "green",
  sap: "green",
  satureja: "fresh-aromatic",
  "saw palmetto": "green",
  seaweed: "water-marine",
  senecio: "green",
  shiso: "green",
  "sideritis mountain tea": "fresh-aromatic",
  "silk vine or milk broom": "green",
  "siriuba tree": "woody",
  "skunk cabbage": "green",
  "snake plant": "green",
  spearmint: "fresh-aromatic",
  spinach: "green",
  "stems greens": "green",
  "strawberry leaf": "green",
  "sugandha kokila": "fresh-aromatic",
  sundew: "green",
  swartzia: "green",
  "sweet grass": "green",
  "tangerine leaves": "green",
  tansy: "fresh-aromatic",
  tarragon: "fresh-aromatic",
  tea: "fresh-aromatic",
  "thai tea": "fresh-aromatic",
  thistle: "green",
  thyme: "fresh-aromatic",
  "ti leaf cordyline": "green",
  "tieguanyin tea": "fresh-aromatic",
  tobacco: "woody-amber",
  "tomato leaf": "green",
  torreya: "woody",
  trees: "woody",
  tulsi: "fresh-aromatic",
  tumbleweed: "dry-woods",
  "turnera diffusa damiana": "green",
  valerian: "green",
  "vanilla leaves": "green",
  vine: "green",
  "violet leaf": "green",
  "water lily leaf": "green",
  wheat: "green",
  "white meranti": "woody",
  "wild carrot": "green",
  "wild garlic leaf": "green",
  "willow-leaved": "green",
  "winter tea": "fresh-aromatic",
  wintergreen: "fresh-aromatic",
  "woodruff or galium odoratum": "green",
  wormwood: "fresh-aromatic",
  yarrow: "green",
  "yunnan red tea": "fresh-aromatic",

  // Spices Family
  allspice: "woody-amber",
  anise: "amber",
  asafoetida: "fresh-aromatic",
  "bay leaf": "fresh-aromatic",
  "bengal pepper": "fresh-aromatic",
  biryani: "fresh-aromatic",
  "black sesame": "woody",
  "cacao pod": "woody-amber",
  caraway: "fresh-aromatic",
  cardamom: "fresh-aromatic",
  "carolina reaper": "fruity",
  carum: "fresh-aromatic",
  cassia: "woody-amber",
  chutney: "fruity",
  cinnamon: "woody-amber",
  "cinnamon leaf": "woody-amber",
  "clove leaf": "woody-amber",
  cloves: "woody-amber",
  coffee: "woody-amber",
  "coffee co2": "woody-amber",
  "coffee tincture": "woody-amber",
  coriander: "fresh-aromatic",
  "cubeb or tailed pepper": "fresh-aromatic",
  cumin: "woody",
  "curcuma turmeric": "woody",
  curry: "fresh-aromatic",
  "curry tree": "fresh-aromatic",
  dill: "green",
  fennel: "fresh-aromatic",
  fenugreek: "soft-amber",
  galanga: "fresh-aromatic",
  ginger: "fresh-aromatic",
  "green coffee": "fresh-aromatic",
  "guinea pepper": "fresh-aromatic",
  "indian spices": "fresh-aromatic",
  "japanese pepper": "fresh-aromatic",
  "kaempferia galanga": "fresh-aromatic",
  "kopi luwak coffee": "fresh-aromatic",
  licorice: "soft-amber",
  mace: "woody-amber",
  "mustard seed": "fresh-aromatic",
  nutmeg: "woody-amber",
  oily: "woody",
  oriental: "amber",
  pepper: "dry-woods",
  peppertree: "woody",
  pimento: "woody-amber",
  "pimento leaf": "woody-amber",
  "pimento seeds": "woody-amber",
  "pink pepper": "floral-amber",
  priprioca: "woody-amber",
  saffron: "amber",
  safraleine: "woody-amber",
  sesame: "woody",
  "siam cardamom": "fresh-aromatic",
  "sichuan pepper": "fresh-aromatic",
  spicy: "fresh-aromatic",
  "spiked pepper": "fresh-aromatic",
  "star anise": "fresh-aromatic",
  sumac: "fresh-aromatic",
  tamarind: "fruity",
  timur: "fresh-aromatic",
  "tonka bean": "amber",
  toscanol: "woody",
  "ultravanil™": "amber",
  vanilla: "soft-amber",
  "wan sao lhong": "fresh-aromatic",
  wasabi: "fresh-aromatic",
  "water pepper": "fresh-aromatic",
  "west indian bay": "fresh-aromatic",

  // Sweets and Gourmand Family
  "acetyl furan": "fruity",
  affogato: "woody-amber",
  "agave nectar": "fruity",
  "apple licor": "fruity",
  "apple pie": "fruity",
  aspic: "fruity",
  "baba italian dessert": "fruity",
  "baked apple": "fruity",
  "baked pear": "fruity",
  baklava: "fruity",
  "banana bread": "fruity",
  biscotti: "woody-amber",
  biscuit: "woody-amber",
  bonbon: "fruity",
  bread: "woody-amber",
  brioche: "woody-amber",
  "brown sugar": "soft-amber",
  brownie: "fruity",
  bubbaloo: "fruity",
  "bubble gum": "fruity",
  "burnt sugar": "amber",
  butter: "fruity",
  buttercream: "fruity",
  butterscotch: "soft-amber",
  "cacao butter": "woody-amber",
  cake: "fruity",
  "calissons d'aix": "fruity",
  "candied fruits": "fruity",
  "candied ginger": "fresh-aromatic",
  "candied orange": "fruity",
  candies: "fruity",
  canelé: "fruity",
  caramel: "soft-amber",
  "cassata siciliana": "fruity",
  cereals: "woody-amber",
  chamallow: "soft-amber",
  "chantilly cream": "soft-amber",
  cheesecake: "fruity",
  "cherry milk": "fruity",
  "cherry syrup": "fruity",
  "chocolate fudge": "fruity",
  "chocolate sauce": "fruity",
  "chocolate truffle": "fruity",
  "choux pastry": "woody-amber",
  churros: "woody-amber",
  "coconut pie": "fruity",
  "coconut powder": "fruity",
  "condensed milk": "soft-amber",
  "cone waffle": "woody-amber",
  "confetti sugared almonds": "fruity",
  cookie: "woody-amber",
  "cookie dough": "woody-amber",
  "cosmofruit™ iff": "fruity",
  "cotton candy": "fruity",
  cream: "soft-amber",
  creamsicle: "fruity",
  "crème brûlée": "soft-amber",
  croissant: "woody-amber",
  cupcake: "fruity",
  custard: "soft-amber",
  "dark chocolate": "woody-amber",
  dates: "fruity",
  "donut or doughnut": "woody-amber",
  dorayaki: "fruity",
  dragee: "fruity",
  dragibus: "fruity",
  "dulce de leche": "soft-amber",
  eggnog: "fruity",
  fougassette: "woody-amber",
  "french pastries": "woody-amber",
  "fresh cream": "soft-amber",
  "frosting glacé": "fruity",
  gelatin: "fruity",
  gianduia: "woody-amber",
  gingerbread: "fresh-aromatic",
  "gourmand accord": "soft-amber",
  "griotte cherries": "fruity",
  "gummy candies": "fruity",
  halva: "fruity",
  "hazelnut cocoa spread": "woody-amber",
  honey: "soft-amber",
  honeycomb: "soft-amber",
  horchata: "fruity",
  "ice cream": "soft-amber",
  "icing pink": "fruity",
  jelly: "fruity",
  jellybean: "fruity",
  "jiuniang sweet fermented rice wine": "fruity",
  knafeh: "fruity",
  kulfi: "fruity",
  "lemon meringue pie": "fruity",
  "lemon pie": "fruity",
  loukhoum: "fruity",
  macarons: "fruity",
  madeleine: "woody-amber",
  "maple syrup": "soft-amber",
  "maraschino cherry": "fruity",
  marmalade: "fruity",
  "marron glacé": "fruity",
  marshmallow: "soft-amber",
  marzipan: "fruity",
  meringues: "fruity",
  "milk candy": "fruity",
  "milk cream": "soft-amber",
  "milk mousse": "soft-amber",
  milkshake: "fruity",
  "milky coffee": "woody-amber",
  molasses: "soft-amber",
  nectar: "fruity",
  nougat: "fruity",
  nutella: "woody-amber",
  oatmilk: "woody-amber",
  "orange gelato": "fruity",
  "palm sugar": "soft-amber",
  pancake: "woody-amber",
  panettone: "fruity",
  "panna cotta": "fruity",
  "pastiera napoletana": "fruity",
  "peach cream": "fruity",
  "peanut butter": "woody-amber",
  "pear ice cream": "fruity",
  "pistachio spread cream": "fruity",
  popcorn: "woody-amber",
  popsicle: "fruity",
  praline: "fruity",
  pretzel: "woody-amber",
  profiterole: "fruity",
  pudding: "fruity",
  "puff pastry": "woody-amber",
  "rainbow sorbet": "fruity",
  "red fruits sorbet": "fruity",
  "rice cake": "woody-amber",
  "rice pudding": "fruity",
  "rose jam": "fruity",
  "rose milk": "fruity",
  "sacher torte": "fruity",
  "salted caramel": "soft-amber",
  "salted caramel fudge": "soft-amber",
  "shortcrust pastry": "woody-amber",
  sorbet: "fruity",
  souffle: "fruity",
  "sour cream": "fruity",
  sprinkles: "fruity",
  "spun sugar": "fruity",
  "strawberry fizz candy": "fruity",
  "strawberry syrup": "fruity",
  sugar: "soft-amber",
  "sugar syrup": "soft-amber",
  "sweet pie": "fruity",
  tartine: "woody-amber",
  tiramisu: "woody-amber",
  toast: "woody-amber",
  "toasted coconut": "fruity",
  toffee: "soft-amber",
  "tropézienne tarte": "fruity",
  tupig: "woody-amber",
  "vanilla caviar": "soft-amber",
  waffle: "woody-amber",
  "white chocolate": "fruity",
  "white chocolate truffle": "fruity",
  "whoopie pie": "fruity",
  yogurt: "fruity",
  zefir: "fruity",

  // Woods and Mosses Family
  "agarwood oud": "woody",
  akigalawood: "woody",
  alder: "woody",
  "almond tree": "woody",
  amaranth: "woody",
  "amburana bark": "woody-amber",
  "amburana wood": "woody",
  amyris: "woody",
  "apple tree": "woody",
  araucaria: "woody",
  "arbutus madrona, bearberry tree": "woody",
  "argan tree": "woody",
  aspen: "woody",
  "australian blue cypress": "woody",
  "australian oud": "woody",
  bamboo: "woody",
  baobab: "woody",
  bark: "woody",
  beech: "woody",
  "belambra tree": "woody",
  birch: "woody",
  "black hemlock or tsuga": "woody",
  "black spruce": "woody",
  blackwood: "woody",
  "blonde woods": "woody",
  "brazilian rosewood": "woody",
  "buddha wood": "woody",
  buxus: "woody",
  cabreuva: "woody",
  "cambodian oud": "woody",
  "canadian balsam": "woody-amber",
  "carob tree": "woody",
  cascarilla: "woody",
  "cashmir wood": "woody",
  cedar: "woody",
  "chalood bark": "woody",
  "charred wood": "dry-woods",
  "cherry tree": "woody",
  "chinese oud": "woody",
  chypre: "mossy-woods",
  clearwood: "woody",
  cocobolo: "woody",
  "coconut tree": "woody",
  "coffee tree": "woody",
  cork: "woody",
  "cottonwood poplar": "woody",
  cypress: "woody",
  "cypriol oil or nagarmotha": "woody",
  "dark patchouli": "woody",
  "dartanol®": "woody",
  "desert sagebrush": "woody",
  "ditax wood": "woody",
  dreamwood: "woody",
  driftwood: "woody",
  "dry wood": "dry-woods",
  ducke: "woody",
  "ebony tree": "woody",
  elm: "woody",
  eucalyptus: "fresh-aromatic",
  "fig tree": "woody",
  fir: "woody",
  "grass tree": "woody",
  "guaiac wood": "woody",
  hiba: "woody",
  "himalayan cedar": "woody",
  "hinoki wood": "woody",
  "ho wood": "woody",
  incienso: "woody",
  "indian oud": "woody",
  "indian sandalwood": "woody",
  "indian woods": "woody",
  ironwood: "woody",
  "ishpink, ocotea quixos": "woody",
  "kenya rosewood": "woody",
  kowhai: "woody",
  "kyara wood": "woody",
  "laotian oud": "woody",
  larch: "woody",
  lichen: "mossy-woods",
  liquidambar: "woody",
  mahogany: "woody",
  "malaysian oud": "woody",
  "mango tree": "woody",
  manuka: "woody",
  maple: "woody",
  massoia: "woody",
  mesquite: "woody",
  "mesquite wood": "woody",
  muhuhu: "woody",
  "mulberry plant": "woody",
  "mysore sandalwood": "woody",
  neem: "woody",
  nootka: "woody",
  oak: "woody",
  oakmoss: "mossy-woods",
  "olive tree": "woody",
  "palisander rosewood": "woody",
  "palo santo": "woody",
  "palo verde tree": "woody",
  pamplewood: "woody",
  paperbark: "woody",
  papyrus: "woody",
  "paraguayan green sandalwood": "woody",
  patchouli: "woody-amber",
  "patchouli green": "woody-amber",
  "peach tree": "woody",
  "pear tree": "woody",
  "pepperwood or hercules club": "woody",
  "phoebe zhennan": "woody",
  "pine tree": "woody",
  "pink ipê tree": "woody",
  "plum tree": "woody",
  "pua keni keni pua-lulu": "floral",
  ravenala: "woody",
  ravensara: "fresh-aromatic",
  "red willow": "woody",
  redwood: "woody",
  "rhizoma atractylodis": "woody",
  saman: "woody",
  "sandalore™": "woody",
  sandalwood: "woody",
  sassafras: "woody",
  satinwood: "woody",
  sawdust: "dry-woods",
  "scots pine variant": "woody",
  "selaginella tamariscina": "mossy-woods",
  sequoia: "woody",
  siam: "woody",
  "siam wood": "woody",
  spruce: "woody",
  sycamore: "woody",
  takamaka: "woody",
  "tamboti wood": "woody",
  tatami: "woody",
  "teak wood": "woody",
  "thailand oud": "woody",
  "thanaka wood": "woody",
  thuja: "woody",
  "transparent woods": "woody",
  vetiver: "woody",
  "vietnamese oud": "woody",
  "white oud": "woody",
  "white willow": "woody",
  wolfwood: "woody",
  "wood barrel": "woody",
  woody: "woody",
  yohimbe: "woody",

  // Resins and Balsams Family
  amberwood: "woody-amber",
  andiroba: "woody",
  bakhoor: "woody-amber",
  balsamic: "amber",
  "balsamic vinegar": "amber",
  benzoin: "soft-amber",
  "birch tar": "woody",
  bisabolene: "woody",
  "blue amber": "amber",
  "bois d'encens": "woody-amber",
  "breu-branco": "woody",
  "bushman candle": "woody-amber",
  "cade oil": "woody",
  "choya loban": "woody-amber",
  "choya nakh": "woody-amber",
  "choya ral": "woody-amber",
  "coal tar": "woody",
  "copahu balm": "amber",
  "copaiba balm": "amber",
  copal: "woody-amber",
  "dragon blood resin": "amber",
  elemi: "woody-amber",
  estoraque: "amber",
  "gurjun balsam": "woody-amber",
  incense: "woody-amber",
  "japanese incense": "woody-amber",
  labdanum: "amber",
  "mastic or lentisque": "woody",
  mopane: "woody",
  myrica: "green",
  myrrh: "woody-amber",
  "nag champa": "woody-amber",
  "olibanum frankincense": "woody-amber",
  "olibanum sacra resin green": "woody-amber",
  opoponax: "amber",
  "peru balsam": "soft-amber",
  "pine tar": "woody",
  "poplar populus buds": "woody",
  resins: "amber",
  rubber: "woody",
  styrax: "amber",
  "surf wax": "woody",
  "tea tree oil": "fresh-aromatic",
  "akashic acord": "amber",
  aldron: "amber",
  amber: "amber",
  "amber xtreme": "amber",
  ambergris: "soft-amber",
  "ambertonic™ iff": "amber",
  ambrarome: "amber",
  ambretone: "soft-amber",
  "ambrette musk mallow": "soft-amber",
  ambrettolide: "soft-amber",
  "ambrocenide symrise": "amber",
  ambrostar: "amber",
  ambroxan: "amber",
  animal: "woody-amber",
  "anthamber™": "amber",
  bacon: "woody-amber",
  bbq: "woody-amber",
  beeswax: "soft-amber",
  cachalox: "amber",
  "carrot seeds": "fresh-aromatic",
  castoreum: "woody-amber",
  caviar: "water-marine",
  cetalox: "amber",
  cheese: "fruity",
  civet: "woody-amber",
  civettone: "woody-amber",
  "coral reef": "water-marine",
  daim: "woody-amber",
  "exaltolide®": "soft-amber",
  feathers: "woody-amber",
  fur: "woody-amber",
  genet: "woody-amber",
  "goat hair": "woody-amber",
  "goat's milk": "soft-amber",
  grisalva: "amber",
  "habanolide®": "soft-amber",
  hyraceum: "woody-amber",
  kephalis: "woody-amber",
  kyphi: "woody-amber",
  leather: "woody-amber",
  meat: "woody-amber",
  milk: "soft-amber",
  muscone: "soft-amber",
  musk: "soft-amber",
  muskrat: "woody-amber",
  oysters: "water-marine",
  "saffiano leather": "woody-amber",
  "sea shells": "water-marine",
  skatole: "woody-amber",
  skin: "woody-amber",
  starfish: "water-marine",
  suede: "woody-amber",
  sylkolide: "soft-amber",
  "tolu balsam": "soft-amber",
  truffle: "woody-amber",
  "velvione™": "soft-amber",

  // Beverages Family
  absinthe: "fresh-aromatic",
  advocaat: "fruity",
  almdudler: "fresh-aromatic",
  amaretto: "fruity",
  amarula: "fruity",
  aperol: "citrus",
  applejack: "fruity",
  "baileys irish cream": "soft-amber",
  batida: "fruity",
  beer: "fresh-aromatic",
  "beer/ale": "fresh-aromatic",
  bellini: "fruity",
  "blackcurrant juice": "fruity",
  "blue margarita": "citrus",
  "bohea wuyi tea": "fresh-aromatic",
  boozy: "woody-amber",
  "bourbon whiskey": "woody-amber",
  "buttered rum": "woody-amber",
  buttermilk: "fruity",
  cachaça: "woody-amber",
  "caffè latte": "woody-amber",
  caipirinha: "citrus",
  "calvados drink": "fruity",
  campari: "fresh-aromatic",
  cappuccino: "woody-amber",
  champagne: "fruity",
  "champagne rosé": "fruity",
  "cherry liqueur": "fruity",
  chinotto: "citrus",
  "coca-cola": "fresh-aromatic",
  "cocktail fruits": "fruity",
  cognac: "woody-amber",
  "cosmopolitan cocktail": "fruity",
  "cream liqueur": "soft-amber",
  "cream soda": "fresh-aromatic",
  curaçao: "citrus",
  daiquiri: "citrus",
  "eau de vie": "fruity",
  espresso: "woody-amber",
  "espresso coffee": "woody-amber",
  "fruit tea": "fruity",
  génépi: "fresh-aromatic",
  gin: "fresh-aromatic",
  goldwasser: "fresh-aromatic",
  grenadine: "fruity",
  "hi-fi": "woody-amber",
  "hot chocolate": "woody-amber",
  "ice wine": "fruity",
  "jasmine tea": "fresh-aromatic",
  "kava drink": "fresh-aromatic",
  "kir royal": "fruity",
  "lemon soda": "citrus",
  lemonade: "citrus",
  limoncello: "citrus",
  liquor: "woody-amber",
  macchiato: "woody-amber",
  madeira: "woody-amber",
  "mai tai cocktail": "fruity",
  margarita: "citrus",
  martini: "fresh-aromatic",
  "masala chai": "fresh-aromatic",
  mezcal: "woody-amber",
  midori: "fruity",
  "mint tea": "fresh-aromatic",
  mocha: "woody-amber",
  mojito: "fresh-aromatic",
  moonshine: "woody-amber",
  "moscow mule": "fresh-aromatic",
  "mulled wine": "fresh-aromatic",
  negroni: "fresh-aromatic",
  "orange soda": "citrus",
  ouzo: "fresh-aromatic",
  "pear juice": "fruity",
  "pina colada": "fruity",
  "pisco sour cocktail": "citrus",
  "pistachio liquer": "fruity",
  "plum liquor": "fruity",
  "plum wine": "fruity",
  "port wine": "woody-amber",
  prosecco: "fruity",
  punch: "fruity",
  raki: "fresh-aromatic",
  "red wine": "woody-amber",
  "rhum agricole": "woody-amber",
  "rice water": "water-marine",
  "root beer": "fresh-aromatic",
  rum: "woody-amber",
  sake: "woody-amber",
  sangria: "fruity",
  "sauce-aroma baijiu": "woody-amber",
  sherry: "woody-amber",
  soju: "fresh-aromatic",
  "sour milk": "fruity",
  "soy milk": "woody-amber",
  "sparkling water": "water-marine",
  "sparkling wine": "fruity",
  syrup: "soft-amber",
  tequila: "fresh-aromatic",
  "tokaji wine": "fruity",
  "tonic water": "fresh-aromatic",
  umeshu: "fruity",
  vermouth: "fresh-aromatic",
  vinegar: "fresh-aromatic",
  vodka: "fresh-aromatic",
  whiskey: "woody-amber",
  "white wine": "fruity",
  "wine lees": "woody-amber",
  "wine must": "fruity",

  // Natural and Synthetic Family
  pepperwood: "woody",
  "accord eudora": "floral-amber",
  "airy note": "water-marine",
  "alcantara accord": "woody-amber",
  aldambre: "amber",
  aldehydes: "fresh-aromatic",
  aluminum: "woody",
  ambreine: "amber",
  ambrettolide: "soft-amber",
  ambrinol: "amber",
  "ambrofix™": "amber",
  "ambrox® super": "amber",
  ammonia: "fresh-aromatic",
  "amyl salicylate": "floral",
  antillone: "floral",
  "apple shisha accord": "fruity",
  aqual: "water-marine",
  aquozone: "water-marine",
  ash: "dry-woods",
  asphalt: "woody",
  azarbre: "woody",
  "black diamond": "woody-amber",
  "black leather": "woody-amber",
  blood: "woody-amber",
  boisiris: "woody",
  bourgeonal: "floral",
  brick: "woody",
  "brown scotch tape": "dry-woods",
  "burnt match": "dry-woods",
  calone: "water-marine",
  calypsone: "water-marine",
  camphor: "fresh-aromatic",
  "candle wax": "soft-amber",
  canvas: "dry-woods",
  caoutchouc: "woody",
  cascalone: "water-marine",
  cashalox: "woody-amber",
  cashmeran: "woody-amber",
  "cetonal®": "woody-amber",
  chalk: "dry-woods",
  cigarette: "woody-amber",
  cinnamaldehyde: "fresh-aromatic",
  clarycet: "fresh-aromatic",
  clay: "dry-woods",
  "co2 extracts": "woody-amber",
  coal: "dry-woods",
  "coal tar pitch": "woody",
  cobblestone: "woody",
  cocaine: "woody-amber",
  concrete: "woody",
  copper: "woody",
  "coral limestone": "water-marine",
  coranol: "woody",
  cork: "woody",
  cosmone: "soft-amber",
  coumarin: "soft-amber",
  "credit cards": "woody",
  crustaceans: "water-marine",
  "cuban cigar": "woody-amber",
  cyclopidene: "floral",
  damascone: "fruity",
  "desert rain accord": "dry-woods",
  "dew drop": "water-marine",
  dihydromyrcenol: "fresh-aromatic",
  dirt: "woody",
  "diving suit": "water-marine",
  dodecanal: "fresh-aromatic",
  dust: "dry-woods",
  "earth tincture": "dry-woods",
  earthy: "dry-woods",
  egg: "fruity",
  ember: "dry-woods",
  "ethyl maltol": "soft-amber",
  eugenol: "fresh-aromatic",
  evernyl: "mossy-woods",
  fabric: "soft-floral",
  "factor x": "woody-amber",
  "fior di latte": "soft-amber",
  fire: "dry-woods",
  fish: "water-marine",
  flint: "dry-woods",
  floralozone: "floral",
  "floratta dna": "floral",
  flour: "dry-woods",
  galaxolide: "soft-amber",
  gasoline: "woody-amber",
  georgywood: "woody",
  geosmin: "dry-woods",
  glass: "water-marine",
  gold: "woody",
  graphite: "woody",
  guaiacol: "woody",
  gunpowder: "dry-woods",
  "hair pomade": "woody-amber",
  "hand cream": "soft-amber",
  hashish: "fresh-aromatic",
  "head space waterfall": "water-marine",
  healingwood: "woody",
  hedione: "floral",
  helvetolide: "soft-amber",
  "hexenyl green": "green",
  "hexyl acetate": "fruity",
  hina: "woody-amber",
  hindinol: "woody",
  "hivernal®": "fresh-aromatic",
  "holy water": "water-marine",
  "hot iron": "dry-woods",
  ice: "fresh-aromatic",
  indole: "floral",
  "industrial glue": "woody",
  ink: "dry-woods",
  inkstick: "dry-woods",
  "instant film accord": "woody-amber",
  ionones: "floral",
  "iso e super": "woody",
  "isobutyl quinoline": "woody-amber",
  jasmolactone: "floral",
  jasmone: "floral",
  javanol: "woody",
  jeans: "dry-woods",
  "lacquered wood": "woody",
  lactones: "fruity",
  latex: "woody",
  lava: "woody",
  "lilybelle®": "floral",
  linen: "soft-floral",
  "lip gloss": "fruity",
  lipstick: "soft-amber",
  "little doll strawberry": "fruity",
  loam: "dry-woods",
  lorenox: "woody",
  magnolan: "floral",
  "mascarpone cheese": "fruity",
  "mayonnaise accord": "fruity",
  melbaton: "fruity",
  melonal: "fruity",
  metallic: "woody",
  mineral: "woody",
  "mitti attar": "dry-woods",
  molasses: "soft-amber",
  money: "woody",
  "motor oil": "woody-amber",
  "mountain air": "fresh-aromatic",
  "mousse de saxe": "mossy-woods",
  mud: "dry-woods",
  mugane: "floral",
  muscenone: "soft-amber",
  mystikal: "fresh-aromatic",
  "nail polish": "woody-amber",
  "naturalcalm™": "soft-floral",
  neoprene: "woody",
  "new magazine": "woody",
  "norlimbanol™": "woody",
  "nympheal™": "floral",
  "old books": "dry-woods",
  "old furniture": "dry-woods",
  "old house": "dry-woods",
  operanide: "floral",
  orbitone: "woody",
  "orcanox™": "amber",
  "osmasylk natsublim™": "soft-floral",
  "oud smoke": "woody",
  ozonic: "water-marine",
  paper: "dry-woods",
  "para-cresyl phenyl acetate": "floral",
  paradisone: "floral",
  parchment: "dry-woods",
  "pearadise®": "fruity",
  pearls: "water-marine",
  peat: "dry-woods",
  pebbles: "woody",
  pencil: "woody",
  petroleum: "woody-amber",
  "pharaone": "woody-amber",
  "pink crystal": "woody",
  "pink himalayan sea salt": "water-marine",
  pizza: "fresh-aromatic",
  plastic: "woody",
  "plastic bag": "woody",
  "play-doh": "woody-amber",
  poison: "woody-amber",
  poivrol: "fresh-aromatic",
  pollen: "floral",
  pomarose: "fruity",
  porcelain: "woody",
  powdery: "soft-floral",
  "priest’s clothes": "woody-amber",
  propolis: "soft-amber",
  prunol: "fruity",
  rain: "water-marine",
  "re base": "woody-amber",
  "red bean paste": "fruity",
  rhodinol: "floral",
  "rice powder": "soft-floral",
  river: "water-marine",
  "romandolide®": "soft-amber",
  "rose oxide": "floral",
  "salicylic acid": "woody-amber",
  salt: "water-marine",
  sand: "dry-woods",
  satin: "soft-floral",
  sauna: "woody",
  "scent trek®": "fresh-aromatic",
  sclarene: "woody-amber",
  "sea foam": "water-marine",
  "sea water": "water-marine",
  serenolide: "soft-amber",
  "shamama attar": "woody-amber",
  silk: "soft-floral",
  silver: "woody",
  sinfonide: "soft-amber",
  siren: "woody",
  "sisal rope": "dry-woods",
  slate: "woody",
  smoke: "woody-amber",
  snow: "fresh-aromatic",
  soap: "fresh-aromatic",
  "sodium silicate": "woody",
  "solar notes": "amber",
  "soy sauce": "woody-amber",
  "sp3 carbon": "woody",
  spiranol: "woody",
  "spray paint": "woody",
  "steam accord": "water-marine",
  stone: "dry-woods",
  straw: "dry-woods",
  "suederal®": "woody-amber",
  sulphur: "fresh-aromatic",
  sunscreen: "soft-amber",
  "suntan lotion": "soft-amber",
  sweat: "woody-amber",
  "t-shirt accord": "dry-woods",
  talc: "soft-floral",
  tar: "woody",
  "tennis ball": "woody",
  terpineol: "fresh-aromatic",
  terracotta: "dry-woods",
  terranol: "woody",
  "thalassogaia™": "water-marine",
  timberol: "woody",
  "timbersilk™": "woody",
  "tomato sauce": "fruity",
  tonalide: "soft-amber",
  "tonquitone™": "woody-amber",
  toothpaste: "fresh-aromatic",
  "trimofix®": "woody",
  tuberolide: "floral",
  "tulle accord": "soft-floral",
  vanillin: "soft-amber",
  "varnish accord": "woody",
  veloutone: "soft-amber",
  velvet: "soft-amber",
  verdox: "green",
  vinyl: "woody",
  "vinyl guaiacol": "woody",
  "vitamin c": "citrus",
  water: "water-marine",
  "western honey bee": "soft-amber",
  "wet plaster": "woody",
  "wet stone": "water-marine",
  "white leather": "woody-amber",
  wool: "woody",
  yeast: "fresh-aromatic",
  "z-11 hd": "woody",

  // Uncategorized
  "canna flower": "floral",
  fog: "water-marine",
  "forest foliage": "green",
  hookah: "woody-amber",
  jonquille: "floral",
  "mangrove wood": "woody",
  nemophila: "floral",
  sorghum: "woody",
  "sweet alyssum": "floral",
  "sweet potato": "fruity",
  umami: "fresh-aromatic",
  vervain: "green",
};
